const about = `
\x1b[91m    _    _                 _   
   / \\  | |__   ___  _   _| |_ 
  / _ \\ | '_ \\ / _ \\| | | | __|
 / ___ \\| |_) | (_) | |_| | |_ 
/_/   \\_\\_.__/ \\___/ \\__,_|\\__|

\x1b[33mThis is a small CLI game written with Node.js
and the first real project made by me.

I decided to implement this kind of game because
I wanted something in the command line that required
automated responses by the script.

\x1b[90m.............................................

\x1b[92m< any > \x1b[94mBack to menu\x1b[0m
`

const menu = `
\x1b[33mCities of
\x1b[90m  ____                                       
 / ___| ___ _ __ _ __ ___   __ _ _ __  _   _ 
\x1b[91m| |  _ / _ \\ '__| '_ \` _ \\ / _\` | '_ \\| | | |
| |_| |  __/ |  | | | | | | (_| | | | | |_| |
\x1b[93m \\____|\\___|_|  |_| |_| |_|\\__,_|_| |_|\\__, |
                                       |___/
\x1b[33mThe Game
\x1b[90m.............................................

\x1b[92m< p > \x1b[94mPlay
\x1b[92m< s > \x1b[94mSettings
\x1b[92m< r > \x1b[94mRules
\x1b[92m< a > \x1b[94mAbout
\x1b[92m< q > \x1b[94mQuit\x1b[0m
`

const rules = [
    `
\x1b[92m ____        _           
|  _ \\ _   _| | ___  ___ 
| |_) | | | | |/ _ \\/ __|
|  _ <| |_| | |  __/\\__ \\
|_| \\_\\\\__,_|_|\\___||___/

\x1b[33mYou are given the name of a German city.

Write the \x1b[36m(German)\x1b[33m name of another one that
starts with the last letter of the given city.
The game is going to repond likewise.

\x1b[90m[ 1/3 ] .....................................

\x1b[92m< n >       \x1b[94mView next page\x1b[0m
\x1b[92m< else >    \x1b[94mBack to menu\x1b[0m
`,
    `

\x1b[33mIf the name of the given city ...

1. ends with 'y' or 'ß':              \x1b[36mBarb\x1b[31my
\x1b[33m2. has a '/' in it:         \x1b[36mGarz\x1b[31m/\x1b[36mRügen

\x1b[33m... then you can just assume that the
previous letter is the last one:

\x1b[36mBar\x1b[31mb\x1b[36my
\x1b[36mGar\x1b[31mz\x1b[36m/Rügen

\x1b[90m[ 2/3 ] .....................................

\x1b[92m< n >       \x1b[94mView next page\x1b[0m
\x1b[92m< else >    \x1b[94mBack to menu\x1b[0m
`,
    `
\x1b[33mYou can use these commands in-game:

\x1b[92m/clear      \x1b[94mClear screen
\x1b[92m/commands   \x1b[94mList available commands
\x1b[92m/quit       \x1b[94mQuit the game
\x1b[92m/stats      \x1b[94mShow your score and HP
\x1b[92m/written    \x1b[94mShow called input




\x1b[90m[ 3/3 ] .....................................

\x1b[92m< n >       \x1b[94mView first page\x1b[0m
\x1b[92m< else >    \x1b[94mBack to menu\x1b[0m
`
]

const commands = `
\x1b[92m/clear      \x1b[94mClear screen
\x1b[92m/commands   \x1b[94mList available commands
\x1b[92m/quit       \x1b[94mQuit the game
\x1b[92m/stats      \x1b[94mShow your score and HP
\x1b[92m/written    \x1b[94mShow called input
`

const settingsBanner = `
\x1b[94m ____       _   _   _                 
/ ___|  ___| |_| |_(_)_ __   __ _ ___ 
\\___ \\ / _ \\ __| __| | '_ \\ / _\` / __|
 ___) |  __/ |_| |_| | | | | (_| \\__ \\
|____/ \\___|\\__|\\__|_|_| |_|\\__, |___/
                            |___/     \x1b[0m
`

const options = `
\x1b[90m.............................................

\x1b[92m< number > \x1b[94mTune setting\x1b[0m
\x1b[92m< else > \x1b[94mBack to menu\x1b[0m
`

const cities = [
    'Aach',
    'Aachen',
    'Aalen',
    'Abenberg',
    'Abensberg',
    'Achern',
    'Achim',
    'Adelsheim',
    'Adenau',
    'Adorf/Vogtl.',
    'Ahaus',
    'Ahlen',
    'Ahrensburg',
    'Aichach',
    'Aichtal',
    'Aken',
    'Albstadt',
    'Alfeld',
    'Allendorf',
    'Allstedt',
    'Alpirsbach',
    'Alsdorf',
    'Alsfeld',
    'Alsleben',
    'Altdorf bei Nürnberg',
    'Altena',
    'Altenberg',
    'Altenburg',
    'Altenkirchen',
    'Altensteig',
    'Altentreptow',
    'Altlandsberg',
    'Altötting',
    'Alzenau',
    'Alzey',
    'Amberg',
    'Amorbach',
    'Amt Creuzburg',
    'Amöneburg',
    'An der Schmücke',
    'Andernach',
    'Angermünde',
    'Anklam',
    'Annaberg-Buchholz',
    'Annaburg',
    'Annweiler am Trifels',
    'Ansbach',
    'Apolda',
    'Arendsee',
    'Arneburg',
    'Arnis',
    'Arnsberg',
    'Arnstadt',
    'Arnstein',
    'Arnstein',
    'Artern',
    'Arzberg',
    'Aschaffenburg',
    'Aschersleben',
    'Asperg',
    'Attendorn',
    'Aub',
    'Aue-Bad Schlema',
    'Auerbach in der Oberpfalz',
    'Auerbach/Vogtl.',
    'Augsburg',
    'Augustusburg',
    'Aulendorf',
    'Auma-Weidatal',
    'Aurich',
    'Aßlar',
    'Babenhausen',
    'Bacharach',
    'Backnang',
    'Bad Aibling',
    'Bad Arolsen',
    'Bad Belzig',
    'Bad Bentheim',
    'Bad Bergzabern',
    'Bad Berka',
    'Bad Berleburg',
    'Bad Berneck im Fichtelgebirge',
    'Bad Bevensen',
    'Bad Bibra',
    'Bad Blankenburg',
    'Bad Bramstedt',
    'Bad Breisig',
    'Bad Brückenau',
    'Bad Buchau',
    'Bad Camberg',
    'Bad Doberan',
    'Bad Driburg',
    'Bad Düben',
    'Bad Dürkheim',
    'Bad Dürrenberg',
    'Bad Dürrheim',
    'Bad Elster',
    'Bad Ems',
    'Bad Fallingbostel',
    'Bad Frankenhausen/Kyffhäuser',
    'Bad Freienwalde',
    'Bad Friedrichshall',
    'Bad Gandersheim',
    'Bad Gottleuba-Berggießhübel',
    'Bad Griesbach im Rottal',
    'Bad Harzburg',
    'Bad Herrenalb',
    'Bad Hersfeld',
    'Bad Homburg vor der Höhe',
    'Bad Honnef',
    'Bad Hönningen',
    'Bad Iburg',
    'Bad Karlshafen',
    'Bad Kissingen',
    'Bad Kreuznach',
    'Bad Krozingen',
    'Bad König',
    'Bad Königshofen im Grabfeld',
    'Bad Köstritz',
    'Bad Kötzting',
    'Bad Laasphe',
    'Bad Langensalza',
    'Bad Lauchstädt',
    'Bad Lausick',
    'Bad Lauterberg im Harz',
    'Bad Liebenstein',
    'Bad Liebenwerda',
    'Bad Liebenzell',
    'Bad Lippspringe',
    'Bad Lobenstein',
    'Bad Marienberg',
    'Bad Mergentheim',
    'Bad Muskau',
    'Bad Münder am Deister',
    'Bad Münstereifel',
    'Bad Nauheim',
    'Bad Nenndorf',
    'Bad Neuenahr-Ahrweiler',
    'Bad Neustadt an der Saale',
    'Bad Oeynhausen',
    'Bad Oldesloe',
    'Bad Orb',
    'Bad Pyrmont',
    'Bad Rappenau',
    'Bad Reichenhall',
    'Bad Rodach',
    'Bad Sachsa',
    'Bad Salzdetfurth',
    'Bad Salzuflen',
    'Bad Salzungen',
    'Bad Saulgau',
    'Bad Schandau',
    'Bad Schmiedeberg',
    'Bad Schussenried',
    'Bad Schwalbach',
    'Bad Schwartau',
    'Bad Segeberg',
    'Bad Sobernheim',
    'Bad Soden am Taunus',
    'Bad Soden-Salmünster',
    'Bad Sooden-Allendorf',
    'Bad Staffelstein',
    'Bad Sulza',
    'Bad Säckingen',
    'Bad Sülze',
    'Bad Teinach-Zavelstein',
    'Bad Tennstedt',
    'Bad Tölz',
    'Bad Urach',
    'Bad Vilbel',
    'Bad Waldsee',
    'Bad Wildbad',
    'Bad Wildungen',
    'Bad Wilsnack',
    'Bad Wimpfen',
    'Bad Windsheim',
    'Bad Wurzach',
    'Bad Wörishofen',
    'Bad Wünnenberg',
    'Baden-Baden',
    'Baesweiler',
    'Baiersdorf',
    'Balingen',
    'Ballenstedt',
    'Balve',
    'Bamberg',
    'Barby',
    'Bargteheide',
    'Barmstedt',
    'Barntrup',
    'Barsinghausen',
    'Barth',
    'Baruth/Mark',
    'Bassum',
    'Battenberg',
    'Baumholder',
    'Baunach',
    'Baunatal',
    'Bautzen',
    'Bayreuth',
    'Bebra',
    'Beckum',
    'Bedburg',
    'Beelitz',
    'Beeskow',
    'Beilngries',
    'Beilstein',
    'Belgern-Schildau',
    'Bendorf',
    'Bensheim',
    'Berching',
    'Berga/Elster',
    'Bergen auf Rügen',
    'Bergen',
    'Bergheim',
    'Bergisch Gladbach',
    'Bergkamen',
    'Bergneustadt',
    'Berlin',
    'Bernau bei Berlin',
    'Bernburg',
    'Bernkastel-Kues',
    'Bernsdorf',
    'Bernstadt a. d. Eigen',
    'Bersenbrück',
    'Besigheim',
    'Betzdorf',
    'Betzenstein',
    'Beverungen',
    'Bexbach',
    'Biberach an der Riß',
    'Biedenkopf',
    'Bielefeld',
    'Biesenthal',
    'Bietigheim-Bissingen',
    'Billerbeck',
    'Bingen am Rhein',
    'Birkenfeld',
    'Bischofsheim in der Rhön',
    'Bischofswerda',
    'Bismark',
    'Bitburg',
    'Bitterfeld-Wolfen',
    'Blankenburg',
    'Blankenhain',
    'Blaubeuren',
    'Blaustein',
    'Bleckede',
    'Bleicherode',
    'Blieskastel',
    'Blomberg',
    'Blumberg',
    'Bobingen',
    'Bocholt',
    'Bochum',
    'Bockenem',
    'Bodenwerder',
    'Bogen',
    'Boizenburg/Elbe',
    'Bonn',
    'Bonndorf im Schwarzwald',
    'Bopfingen',
    'Boppard',
    'Borgentreich',
    'Borgholzhausen',
    'Borken',
    'Borken',
    'Borkum',
    'Borna',
    'Bornheim',
    'Bottrop',
    'Boxberg',
    'Brackenheim',
    'Brake',
    'Brakel',
    'Bramsche',
    'Brand-Erbisdorf',
    'Brandenburg an der Havel',
    'Brandis',
    'Braubach',
    'Braunfels',
    'Braunlage',
    'Braunsbedra',
    'Braunschweig',
    'Breckerfeld',
    'Bredstedt',
    'Breisach am Rhein',
    'Bremen',
    'Bremerhaven',
    'Bremervörde',
    'Bretten',
    'Breuberg',
    'Brilon',
    'Brotterode-Trusetal',
    'Bruchköbel',
    'Bruchsal',
    'Brunsbüttel',
    'Bräunlingen',
    'Brück',
    'Brüel',
    'Brühl',
    'Brüssow',
    'Buchen',
    'Buchholz in der Nordheide',
    'Buchloe',
    'Buckow',
    'Burg Stargard',
    'Burg',
    'Burgau',
    'Burgbernheim',
    'Burgdorf',
    'Burghausen',
    'Burgkunstadt',
    'Burglengenfeld',
    'Burgstädt',
    'Burgwedel',
    'Burladingen',
    'Burscheid',
    'Butzbach',
    'Buxtehude',
    'Bärnau',
    'Böblingen',
    'Böhlen',
    'Bönnigheim',
    'Bückeburg',
    'Büdelsdorf',
    'Büdingen',
    'Bühl',
    'Bünde',
    'Büren',
    'Bürgel',
    'Bürstadt',
    'Bützow',
    'Calau',
    'Calbe',
    'Calw',
    'Castrop-Rauxel',
    'Celle',
    'Cham',
    'Chemnitz',
    'Clausthal-Zellerfeld',
    'Clingen',
    'Cloppenburg',
    'Coburg',
    'Cochem',
    'Coesfeld',
    'Colditz',
    'Coswig',
    'Coswig',
    'Cottbus',
    'Crailsheim',
    'Creglingen',
    'Creußen',
    'Crimmitschau',
    'Crivitz',
    'Cuxhaven',
    'Daaden',
    'Dachau',
    'Dahlen',
    'Dahme/Mark',
    'Dahn',
    'Damme',
    'Dannenberg',
    'Dargun',
    'Darmstadt',
    'Dassel',
    'Dassow',
    'Datteln',
    'Daun',
    'Deggendorf',
    'Deidesheim',
    'Delbrück',
    'Delitzsch',
    'Delmenhorst',
    'Demmin',
    'Dessau-Roßlau',
    'Detmold',
    'Dettelbach',
    'Dieburg',
    'Diemelstadt',
    'Diepholz',
    'Dierdorf',
    'Dietenheim',
    'Dietfurt an der Altmühl',
    'Dietzenbach',
    'Diez',
    'Dillenburg',
    'Dillingen an der Donau',
    'Dillingen/Saar',
    'Dingelstädt',
    'Dingolfing',
    'Dinkelsbühl',
    'Dinklage',
    'Dinslaken',
    'Dippoldiswalde',
    'Dissen am Teutoburger Wald',
    'Ditzingen',
    'Doberlug-Kirchhain',
    'Dohna',
    'Dommitzsch',
    'Donaueschingen',
    'Donauwörth',
    'Donzdorf',
    'Dorfen',
    'Dormagen',
    'Dornburg-Camburg',
    'Dornhan',
    'Dornstetten',
    'Dorsten',
    'Dortmund',
    'Dransfeld',
    'Drebkau',
    'Dreieich',
    'Drensteinfurt',
    'Dresden',
    'Drolshagen',
    'Duderstadt',
    'Duisburg',
    'Döbeln',
    'Döbern',
    'Dömitz',
    'Dülmen',
    'Düren',
    'Düsseldorf',
    'Ebeleben',
    'Eberbach',
    'Ebermannstadt',
    'Ebern',
    'Ebersbach an der Fils',
    'Ebersbach-Neugersdorf',
    'Ebersberg',
    'Eberswalde',
    'Eckartsberga',
    'Eckernförde',
    'Edenkoben',
    'Egeln',
    'Eggenfelden',
    'Eggesin',
    'Ehingen',
    'Ehrenfriedersdorf',
    'Eibelstadt',
    'Eibenstock',
    'Eichstätt',
    'Eilenburg',
    'Einbeck',
    'Eisenach',
    'Eisenberg',
    'Eisenberg',
    'Eisenhüttenstadt',
    'Eisfeld',
    'Eisleben',
    'Eislingen/Fils',
    'Ellingen',
    'Ellrich',
    'Ellwangen',
    'Elmshorn',
    'Elsdorf',
    'Elsfleth',
    'Elsterberg',
    'Elsterwerda',
    'Elstra',
    'Elterlein',
    'Eltmann',
    'Eltville am Rhein',
    'Elzach',
    'Elze',
    'Emden',
    'Emmelshausen',
    'Emmendingen',
    'Emmerich am Rhein',
    'Emsdetten',
    'Endingen am Kaiserstuhl',
    'Engen',
    'Enger',
    'Ennepetal',
    'Ennigerloh',
    'Eppelheim',
    'Eppingen',
    'Eppstein',
    'Erbach',
    'Erbach',
    'Erbendorf',
    'Erding',
    'Erftstadt',
    'Erfurt',
    'Erkelenz',
    'Erkner',
    'Erkrath',
    'Erlangen',
    'Erlenbach am Main',
    'Erlensee',
    'Erwitte',
    'Eschborn',
    'Eschenbach in der Oberpfalz',
    'Eschershausen',
    'Eschwege',
    'Eschweiler',
    'Esens',
    'Espelkamp',
    'Essen',
    'Esslingen am Neckar',
    'Ettenheim',
    'Ettlingen',
    'Euskirchen',
    'Eutin',
    'Falkenberg/Elster',
    'Falkensee',
    'Falkenstein/Harz',
    'Falkenstein/Vogtl.',
    'Fehmarn',
    'Fellbach',
    'Felsberg',
    'Feuchtwangen',
    'Filderstadt',
    'Finsterwalde',
    'Fladungen',
    'Flensburg',
    'Florstadt',
    'Flöha',
    'Flörsheim am Main',
    'Forchheim',
    'Forchtenberg',
    'Forst',
    'Frankenau',
    'Frankenberg',
    'Frankenberg/Sa.',
    'Frankenthal',
    'Frankfurt am Main',
    'Frankfurt an der Oder',
    'Franzburg',
    'Frauenstein',
    'Frechen',
    'Freiberg am Neckar',
    'Freiberg',
    'Freiburg im Breisgau',
    'Freilassing',
    'Freinsheim',
    'Freising',
    'Freital',
    'Freren',
    'Freudenberg',
    'Freudenberg',
    'Freudenstadt',
    'Freyburg',
    'Freystadt',
    'Freyung',
    'Fridingen an der Donau',
    'Friedberg',
    'Friedberg',
    'Friedland',
    'Friedland',
    'Friedrichroda',
    'Friedrichsdorf',
    'Friedrichshafen',
    'Friedrichstadt',
    'Friedrichsthal',
    'Friesack',
    'Friesoythe',
    'Fritzlar',
    'Frohburg',
    'Fröndenberg/Ruhr',
    'Fulda',
    'Furth im Wald',
    'Furtwangen im Schwarzwald',
    'Fürstenau',
    'Fürstenberg/Havel',
    'Fürstenfeldbruck',
    'Fürstenwalde/Spree',
    'Fürth',
    'Füssen',
    'Gadebusch',
    'Gaggenau',
    'Gaildorf',
    'Gammertingen',
    'Garbsen',
    'Garching bei München',
    'Gardelegen',
    'Garding',
    'Gartz',
    'Garz/Rügen',
    'Gau-Algesheim',
    'Gebesee',
    'Gedern',
    'Geesthacht',
    'Geestland',
    'Gefell',
    'Gefrees',
    'Gehrden',
    'Geilenkirchen',
    'Geisa',
    'Geiselhöring',
    'Geisenfeld',
    'Geisenheim',
    'Geisingen',
    'Geislingen an der Steige',
    'Geislingen',
    'Geithain',
    'Geldern',
    'Gelnhausen',
    'Gelsenkirchen',
    'Gemünden',
    'Gemünden am Main',
    'Gengenbach',
    'Genthin',
    'Georgsmarienhütte',
    'Gera',
    'Gerabronn',
    'Gerbstedt',
    'Geretsried',
    'Geringswalde',
    'Gerlingen',
    'Germering',
    'Germersheim',
    'Gernsbach',
    'Gernsheim',
    'Gerolstein',
    'Gerolzhofen',
    'Gersfeld',
    'Gersthofen',
    'Gescher',
    'Geseke',
    'Gevelsberg',
    'Geyer',
    'Giengen an der Brenz',
    'Gießen',
    'Gifhorn',
    'Ginsheim-Gustavsburg',
    'Gladbeck',
    'Gladenbach',
    'Glashütte',
    'Glauchau',
    'Glinde',
    'Glücksburg',
    'Glückstadt',
    'Gnoien',
    'Goch',
    'Goldberg',
    'Goldkronach',
    'Golßen',
    'Gommern',
    'Goslar',
    'Gotha',
    'Grabow',
    'Grafenau',
    'Grafenwöhr',
    'Grafing bei München',
    'Gransee',
    'Grebenau',
    'Grebenstein',
    'Greding',
    'Greifswald',
    'Greiz',
    'Greußen',
    'Greven',
    'Grevenbroich',
    'Grevesmühlen',
    'Griesheim',
    'Grimma',
    'Grimmen',
    'Groitzsch',
    'Gronau',
    'Gronau',
    'Groß-Bieberau',
    'Groß-Gerau',
    'Groß-Umstadt',
    'Großalmerode',
    'Großbottwar',
    'Großbreitenbach',
    'Großenhain',
    'Großräschen',
    'Großröhrsdorf',
    'Großschirma',
    'Gräfenberg',
    'Gräfenhainichen',
    'Gräfenthal',
    'Gröditz',
    'Gröningen',
    'Grünberg',
    'Grünhain-Beierfeld',
    'Grünsfeld',
    'Grünstadt',
    'Guben',
    'Gudensberg',
    'Gummersbach',
    'Gundelfingen an der Donau',
    'Gundelsheim',
    'Gunzenhausen',
    'Göppingen',
    'Görlitz',
    'Göttingen',
    'Gößnitz',
    'Güglingen',
    'Günzburg',
    'Güsten',
    'Güstrow',
    'Gütersloh',
    'Gützkow',
    'Haan',
    'Hachenburg',
    'Hadamar',
    'Hagen',
    'Hagenbach',
    'Hagenow',
    'Haiger',
    'Haigerloch',
    'Hainichen',
    'Haiterbach',
    'Halberstadt',
    'Haldensleben',
    'Halle',
    'Halle',
    'Hallenberg',
    'Hallstadt',
    'Haltern am See',
    'Halver',
    'Hamburg',
    'Hameln',
    'Hamm',
    'Hammelburg',
    'Hamminkeln',
    'Hanau',
    'Hann. Münden',
    'Hannover',
    'Harburg',
    'Hardegsen',
    'Haren',
    'Harsewinkel',
    'Hartenstein',
    'Hartha',
    'Harzgerode',
    'Haselünne',
    'Haslach im Kinzigtal',
    'Hattersheim am Main',
    'Hattingen',
    'Hatzfeld',
    'Hausach',
    'Hauzenberg',
    'Havelberg',
    'Havelsee',
    'Hayingen',
    'Haßfurt',
    'Hechingen',
    'Hecklingen',
    'Heide',
    'Heideck',
    'Heidelberg',
    'Heidenau',
    'Heidenheim an der Brenz',
    'Heilbad Heiligenstadt',
    'Heilbronn',
    'Heiligenhafen',
    'Heiligenhaus',
    'Heilsbronn',
    'Heimbach',
    'Heimsheim',
    'Heinsberg',
    'Heitersheim',
    'Heldburg',
    'Helmbrechts',
    'Helmstedt',
    'Hemau',
    'Hemer',
    'Hemmingen',
    'Hemmoor',
    'Hemsbach',
    'Hennef',
    'Hennigsdorf',
    'Heppenheim',
    'Herbolzheim',
    'Herborn',
    'Herbrechtingen',
    'Herbstein',
    'Herdecke',
    'Herdorf',
    'Herford',
    'Heringen',
    'Heringen/Helme',
    'Hermeskeil',
    'Hermsdorf',
    'Herne',
    'Herrenberg',
    'Herrieden',
    'Herrnhut',
    'Hersbruck',
    'Herten',
    'Herzberg',
    'Herzberg am Harz',
    'Herzogenaurach',
    'Herzogenrath',
    'Hessisch Lichtenau',
    'Hessisch Oldendorf',
    'Hettingen',
    'Hettstedt',
    'Heubach',
    'Heusenstamm',
    'Hilchenbach',
    'Hildburghausen',
    'Hilden',
    'Hildesheim',
    'Hillesheim',
    'Hilpoltstein',
    'Hirschau',
    'Hirschberg',
    'Hirschhorn',
    'Hitzacker',
    'Hochheim am Main',
    'Hockenheim',
    'Hof',
    'Hofgeismar',
    'Hofheim am Taunus',
    'Hofheim in Unterfranken',
    'Hohen Neuendorf',
    'Hohenberg an der Eger',
    'Hohenleuben',
    'Hohenmölsen',
    'Hohenstein-Ernstthal',
    'Hohnstein',
    'Hollfeld',
    'Holzgerlingen',
    'Holzminden',
    'Homberg',
    'Homberg',
    'Homburg',
    'Horb am Neckar',
    'Horn-Bad Meinberg',
    'Hornbach',
    'Hornberg',
    'Horstmar',
    'Hoya',
    'Hoyerswerda',
    'Hungen',
    'Husum',
    'Höchstadt an der Aisch',
    'Höchstädt an der Donau',
    'Höhr-Grenzhausen',
    'Hörstel',
    'Höxter',
    'Hückelhoven',
    'Hückeswagen',
    'Hüfingen',
    'Hünfeld',
    'Hürth',
    'Ibbenbüren',
    'Ichenhausen',
    'Idar-Oberstein',
    'Idstein',
    'Illertissen',
    'Ilmenau',
    'Ilsenburg',
    'Ilshofen',
    'Immenhausen',
    'Immenstadt im Allgäu',
    'Ingelfingen',
    'Ingelheim am Rhein',
    'Ingolstadt',
    'Iphofen',
    'Iserlohn',
    'Isny im Allgäu',
    'Isselburg',
    'Itzehoe',
    'Jarmen',
    'Jena',
    'Jerichow',
    'Jessen',
    'Jever',
    'Joachimsthal',
    'Johanngeorgenstadt',
    'Jöhstadt',
    'Jüchen',
    'Jülich',
    'Jüterbog',
    'Kaarst',
    'Kahla',
    'Kaisersesch',
    'Kaiserslautern',
    'Kalbe',
    'Kalkar',
    'Kaltenkirchen',
    'Kaltennordheim',
    'Kamen',
    'Kamenz',
    'Kamp-Lintfort',
    'Kandel',
    'Kandern',
    'Kappeln',
    'Karben',
    'Karlsruhe',
    'Karlstadt',
    'Kassel',
    'Kastellaun',
    'Katzenelnbogen',
    'Kaub',
    'Kaufbeuren',
    'Kehl',
    'Kelbra',
    'Kelheim',
    'Kelkheim',
    'Kellinghusen',
    'Kelsterbach',
    'Kemberg',
    'Kemnath',
    'Kempen',
    'Kempten',
    'Kenzingen',
    'Kerpen',
    'Ketzin/Havel',
    'Kevelaer',
    'Kiel',
    'Kierspe',
    'Kirchberg',
    'Kirchberg an der Jagst',
    'Kirchberg',
    'Kirchen',
    'Kirchenlamitz',
    'Kirchhain',
    'Kirchheim unter Teck',
    'Kirchheimbolanden',
    'Kirn',
    'Kirtorf',
    'Kitzingen',
    'Kitzscher',
    'Kleve',
    'Klingenberg am Main',
    'Klingenthal',
    'Klötze',
    'Klütz',
    'Knittlingen',
    'Koblenz',
    'Kolbermoor',
    'Konstanz',
    'Konz',
    'Korbach',
    'Korntal-Münchingen',
    'Kornwestheim',
    'Korschenbroich',
    'Kraichtal',
    'Krakow am See',
    'Kranichfeld',
    'Krautheim',
    'Krefeld',
    'Kremmen',
    'Krempe',
    'Kreuztal',
    'Kronach',
    'Kronberg im Taunus',
    'Kroppenstedt',
    'Krumbach',
    'Kröpelin',
    'Kulmbach',
    'Kupferberg',
    'Kuppenheim',
    'Kusel',
    'Kyllburg',
    'Kyritz',
    'Kölleda',
    'Köln',
    'Königs Wusterhausen',
    'Königsberg in Bayern',
    'Königsbrunn',
    'Königsbrück',
    'Königsee',
    'Königslutter am Elm',
    'Königstein',
    'Königstein im Taunus',
    'Königswinter',
    'Könnern',
    'Köthen',
    'Kühlungsborn',
    'Külsheim',
    'Künzelsau',
    'Laage',
    'Laatzen',
    'Ladenburg',
    'Lage',
    'Lahnstein',
    'Lahr/Schwarzwald',
    'Laichingen',
    'Lambrecht',
    'Lampertheim',
    'Landau an der Isar',
    'Landau in der Pfalz',
    'Landsberg am Lech',
    'Landsberg',
    'Landshut',
    'Landstuhl',
    'Langelsheim',
    'Langen',
    'Langenau',
    'Langenburg',
    'Langenfeld',
    'Langenhagen',
    'Langenselbold',
    'Langenzenn',
    'Lassan',
    'Laubach',
    'Laucha an der Unstrut',
    'Lauchhammer',
    'Lauchheim',
    'Lauda-Königshofen',
    'Lauenburg/Elbe',
    'Lauf an der Pegnitz',
    'Laufen',
    'Laufenburg',
    'Lauffen am Neckar',
    'Lauingen',
    'Laupheim',
    'Lauscha',
    'Lauta',
    'Lauter-Bernsbach',
    'Lauterbach',
    'Lauterecken',
    'Lauterstein',
    'Lebach',
    'Lebus',
    'Leer',
    'Lehesten',
    'Lehrte',
    'Leichlingen',
    'Leimen',
    'Leinefelde-Worbis',
    'Leinfelden-Echterdingen',
    'Leingarten',
    'Leipheim',
    'Leipzig',
    'Leisnig',
    'Lemgo',
    'Lengenfeld',
    'Lengerich',
    'Lennestadt',
    'Lenzen',
    'Leonberg',
    'Leun',
    'Leuna',
    'Leutenberg',
    'Leutershausen',
    'Leutkirch im Allgäu',
    'Leverkusen',
    'Lich',
    'Lichtenau',
    'Lichtenau',
    'Lichtenberg',
    'Lichtenfels',
    'Lichtenfels',
    'Lichtenstein/Sa.',
    'Liebenau',
    'Liebenwalde',
    'Lieberose',
    'Liebstadt',
    'Limbach-Oberfrohna',
    'Limburg an der Lahn',
    'Lindau',
    'Linden',
    'Lindenberg im Allgäu',
    'Lindenfels',
    'Lindow',
    'Lingen',
    'Linnich',
    'Linz am Rhein',
    'Lippstadt',
    'Lohmar',
    'Lohne',
    'Lohr am Main',
    'Loitz',
    'Lollar',
    'Lommatzsch',
    'Lorch',
    'Lorch',
    'Lorsch',
    'Lucka',
    'Luckau',
    'Luckenwalde',
    'Ludwigsburg',
    'Ludwigsfelde',
    'Ludwigshafen am Rhein',
    'Ludwigslust',
    'Ludwigsstadt',
    'Lugau',
    'Lunzenau',
    'Lychen',
    'Löbau',
    'Löffingen',
    'Löhne',
    'Löningen',
    'Lörrach',
    'Löwenstein',
    'Lößnitz',
    'Lübbecke',
    'Lübben',
    'Lübbenau/Spreewald',
    'Lübeck',
    'Lübtheen',
    'Lübz',
    'Lüchow',
    'Lüdenscheid',
    'Lüdinghausen',
    'Lügde',
    'Lüneburg',
    'Lünen',
    'Lütjenburg',
    'Lützen',
    'Magdala',
    'Magdeburg',
    'Mahlberg',
    'Mainbernheim',
    'Mainburg',
    'Maintal',
    'Mainz',
    'Malchin',
    'Malchow',
    'Manderscheid',
    'Mannheim',
    'Mansfeld',
    'Marbach am Neckar',
    'Marburg',
    'Marienberg',
    'Marienmünster',
    'Markdorf',
    'Markgröningen',
    'Markkleeberg',
    'Markneukirchen',
    'Markranstädt',
    'Marktbreit',
    'Marktheidenfeld',
    'Marktleuthen',
    'Marktoberdorf',
    'Marktredwitz',
    'Marktsteft',
    'Marl',
    'Marlow',
    'Marne',
    'Marsberg',
    'Maulbronn',
    'Maxhütte-Haidhof',
    'Mayen',
    'Mechernich',
    'Meckenheim',
    'Medebach',
    'Meerane',
    'Meerbusch',
    'Meersburg',
    'Meinerzhagen',
    'Meiningen',
    'Meisenheim',
    'Meißen',
    'Meldorf',
    'Melle',
    'Mellrichstadt',
    'Melsungen',
    'Memmingen',
    'Menden',
    'Mendig',
    'Mengen',
    'Meppen',
    'Merkendorf',
    'Merseburg',
    'Merzig',
    'Meschede',
    'Mettmann',
    'Metzingen',
    'Meuselwitz',
    'Meyenburg',
    'Meßkirch',
    'Meßstetten',
    'Michelstadt',
    'Miesbach',
    'Miltenberg',
    'Mindelheim',
    'Minden',
    'Mirow',
    'Mittenwalde',
    'Mitterteich',
    'Mittweida',
    'Moers',
    'Monheim am Rhein',
    'Monheim',
    'Monschau',
    'Montabaur',
    'Moosburg an der Isar',
    'Moringen',
    'Mosbach',
    'Munderkingen',
    'Munster',
    'Murrhardt',
    'Märkisch Buchholz',
    'Möckern',
    'Möckmühl',
    'Mölln',
    'Mönchengladbach',
    'Mörfelden-Walldorf',
    'Mössingen',
    'Mücheln',
    'Mügeln',
    'Mühlacker',
    'Mühlberg/Elbe',
    'Mühldorf am Inn',
    'Mühlhausen/Thüringen',
    'Mühlheim am Main',
    'Mühlheim an der Donau',
    'Mülheim an der Ruhr',
    'Mülheim-Kärlich',
    'Müllheim',
    'Müllrose',
    'Münchberg',
    'Müncheberg',
    'München',
    'Münchenbernsdorf',
    'Münnerstadt',
    'Münsingen',
    'Münster',
    'Münstermaifeld',
    'Münzenberg',
    'Nabburg',
    'Nagold',
    'Naila',
    'Nassau',
    'Nastätten',
    'Nauen',
    'Naumburg',
    'Naumburg',
    'Naunhof',
    'Nebra',
    'Neckarbischofsheim',
    'Neckargemünd',
    'Neckarsteinach',
    'Neckarsulm',
    'Neresheim',
    'Netphen',
    'Nettetal',
    'Netzschkau',
    'Neu-Anspach',
    'Neu-Isenburg',
    'Neu-Ulm',
    'Neubrandenburg',
    'Neubukow',
    'Neubulach',
    'Neuburg an der Donau',
    'Neudenau',
    'Neuenburg am Rhein',
    'Neuenbürg',
    'Neuenhaus',
    'Neuenrade',
    'Neuenstadt am Kocher',
    'Neuenstein',
    'Neuerburg',
    'Neuffen',
    'Neuhaus am Rennweg',
    'Neukalen',
    'Neukirchen',
    'Neukirchen-Vluyn',
    'Neukloster',
    'Neumark',
    'Neumarkt in der Oberpfalz',
    'Neumarkt-Sankt Veit',
    'Neumünster',
    'Neunburg vorm Wald',
    'Neunkirchen',
    'Neuruppin',
    'Neusalza-Spremberg',
    'Neuss',
    'Neustadt',
    'Neustadt',
    'Neustadt am Kulm',
    'Neustadt am Rübenberge',
    'Neustadt an der Aisch',
    'Neustadt an der Donau',
    'Neustadt an der Orla',
    'Neustadt an der Waldnaab',
    'Neustadt an der Weinstraße',
    'Neustadt bei Coburg',
    'Neustadt in Holstein',
    'Neustadt in Sachsen',
    'Neustadt-Glewe',
    'Neustrelitz',
    'Neusäß',
    'Neutraubling',
    'Neuwied',
    'Neuötting',
    'Nidda',
    'Niddatal',
    'Nidderau',
    'Nideggen',
    'Niebüll',
    'Niedenstein',
    'Nieder-Olm',
    'Niederkassel',
    'Niedernhall',
    'Niederstetten',
    'Niederstotzingen',
    'Nieheim',
    'Niemegk',
    'Nienburg',
    'Nienburg/Weser',
    'Nierstein',
    'Niesky',
    'Nittenau',
    'Norden',
    'Nordenham',
    'Norderney',
    'Norderstedt',
    'Nordhausen',
    'Nordhorn',
    'Northeim',
    'Nortorf',
    'Nossen',
    'Nottertal-Heilinger Höhen',
    'Nördlingen',
    'Nürnberg',
    'Nürtingen',
    'Ober-Ramstadt',
    'Oberasbach',
    'Oberharz am Brocken',
    'Oberhausen',
    'Oberhof',
    'Oberkirch',
    'Oberkochen',
    'Oberlungwitz',
    'Obermoschel',
    'Obernburg am Main',
    'Oberndorf am Neckar',
    'Obernkirchen',
    'Oberriexingen',
    'Obertshausen',
    'Oberursel',
    'Oberviechtach',
    'Oberwesel',
    'Oberwiesenthal',
    'Oberzent',
    'Ochsenfurt',
    'Ochsenhausen',
    'Ochtrup',
    'Oderberg',
    'Oebisfelde-Weferlingen',
    'Oederan',
    'Oelde',
    'Oelsnitz/Erzgeb.',
    'Oelsnitz/Vogtl.',
    'Oer-Erkenschwick',
    'Oerlinghausen',
    'Oestrich-Winkel',
    'Oettingen in Bayern',
    'Offenbach am Main',
    'Offenburg',
    'Ohrdruf',
    'Olbernhau',
    'Olching',
    'Oldenburg',
    'Oldenburg in Holstein',
    'Olfen',
    'Olpe',
    'Olsberg',
    'Oppenau',
    'Oppenheim',
    'Oranienbaum-Wörlitz',
    'Oranienburg',
    'Orlamünde',
    'Ornbau',
    'Ortenberg',
    'Ortrand',
    'Oschatz',
    'Oschersleben',
    'Osnabrück',
    'Osterburg',
    'Osterburken',
    'Osterfeld',
    'Osterhofen',
    'Osterholz-Scharmbeck',
    'Osterode am Harz',
    'Osterwieck',
    'Ostfildern',
    'Ostheim vor der Rhön',
    'Osthofen',
    'Ostritz',
    'Otterberg',
    'Otterndorf',
    'Ottweiler',
    'Overath',
    'Owen',
    'Paderborn',
    'Papenburg',
    'Pappenheim',
    'Parchim',
    'Parsberg',
    'Pasewalk',
    'Passau',
    'Pattensen',
    'Pausa-Mühltroff',
    'Pegau',
    'Pegnitz',
    'Peine',
    'Peitz',
    'Penig',
    'Penkun',
    'Penzberg',
    'Penzlin',
    'Perleberg',
    'Petershagen',
    'Pfaffenhofen an der Ilm',
    'Pfarrkirchen',
    'Pforzheim',
    'Pfreimd',
    'Pfullendorf',
    'Pfullingen',
    'Pfungstadt',
    'Philippsburg',
    'Pinneberg',
    'Pirmasens',
    'Pirna',
    'Plattling',
    'Plau am See',
    'Plaue',
    'Plauen',
    'Plettenberg',
    'Pleystein',
    'Plochingen',
    'Plön',
    'Pockau-Lengefeld',
    'Pocking',
    'Pohlheim',
    'Polch',
    'Porta Westfalica',
    'Potsdam',
    'Pottenstein',
    'Preetz',
    'Premnitz',
    'Prenzlau',
    'Pressath',
    'Preußisch Oldendorf',
    'Prichsenstadt',
    'Pritzwalk',
    'Prüm',
    'Puchheim',
    'Pulheim',
    'Pulsnitz',
    'Putbus',
    'Putlitz',
    'Pößneck',
    'Püttlingen',
    'Quakenbrück',
    'Quedlinburg',
    'Querfurt',
    'Quickborn',
    'Rabenau',
    'Radeberg',
    'Radebeul',
    'Radeburg',
    'Radevormwald',
    'Radolfzell am Bodensee',
    'Raguhn-Jeßnitz',
    'Rahden',
    'Rain',
    'Ramstein-Miesenbach',
    'Ranis',
    'Ransbach-Baumbach',
    'Rastatt',
    'Rastenberg',
    'Rathenow',
    'Ratingen',
    'Ratzeburg',
    'Rauenberg',
    'Raunheim',
    'Rauschenberg',
    'Ravensburg',
    'Ravenstein',
    'Recklinghausen',
    'Rees',
    'Regen',
    'Regensburg',
    'Regis-Breitingen',
    'Rehau',
    'Rehburg-Loccum',
    'Rehna',
    'Reichelsheim',
    'Reichenbach im Vogtland',
    'Reichenbach/O.L.',
    'Reinbek',
    'Reinfeld',
    'Reinheim',
    'Remagen',
    'Remscheid',
    'Remseck am Neckar',
    'Renchen',
    'Rendsburg',
    'Rennerod',
    'Renningen',
    'Rerik',
    'Rethem',
    'Reutlingen',
    'Rheda-Wiedenbrück',
    'Rhede',
    'Rheinau',
    'Rheinbach',
    'Rheinberg',
    'Rheinböllen',
    'Rheine',
    'Rheinfelden',
    'Rheinsberg',
    'Rheinstetten',
    'Rhens',
    'Rhinow',
    'Ribnitz-Damgarten',
    'Richtenberg',
    'Riedenburg',
    'Riedlingen',
    'Riedstadt',
    'Rieneck',
    'Riesa',
    'Rietberg',
    'Rinteln',
    'Rochlitz',
    'Rockenhausen',
    'Rodalben',
    'Rodenberg',
    'Rodewisch',
    'Rodgau',
    'Roding',
    'Romrod',
    'Ronneburg',
    'Ronnenberg',
    'Rosbach vor der Höhe',
    'Rosenfeld',
    'Rosenheim',
    'Rosenthal',
    'Rostock',
    'Rotenburg',
    'Rotenburg an der Fulda',
    'Roth',
    'Rothenburg ob der Tauber',
    'Rothenburg/O.L.',
    'Rothenfels',
    'Rottenburg a.d.Laaber',
    'Rottenburg am Neckar',
    'Rottweil',
    'Roßleben-Wiehe',
    'Roßwein',
    'Rudolstadt',
    'Ruhla',
    'Ruhland',
    'Runkel',
    'Rutesheim',
    'Röbel/Müritz',
    'Rödental',
    'Rödermark',
    'Römhild',
    'Rösrath',
    'Rötha',
    'Röthenbach an der Pegnitz',
    'Röttingen',
    'Rötz',
    'Rüdesheim am Rhein',
    'Rüsselsheim am Main',
    'Rüthen',
    'Saalburg-Ebersdorf',
    'Saalfeld/Saale',
    'Saarbrücken',
    'Saarburg',
    'Saarlouis',
    'Sachsenhagen',
    'Sachsenheim',
    'Salzgitter',
    'Salzkotten',
    'Salzwedel',
    'Sandau',
    'Sandersdorf-Brehna',
    'Sangerhausen',
    'Sankt Augustin',
    'Sankt Goar',
    'Sankt Goarshausen',
    'Sarstedt',
    'Sassenberg',
    'Sassnitz',
    'Sayda',
    'Schalkau',
    'Schauenstein',
    'Scheer',
    'Scheibenberg',
    'Scheinfeld',
    'Schelklingen',
    'Schenefeld',
    'Scheßlitz',
    'Schieder-Schwalenberg',
    'Schifferstadt',
    'Schillingsfürst',
    'Schiltach',
    'Schirgiswalde-Kirschau',
    'Schkeuditz',
    'Schkölen',
    'Schleiden',
    'Schleiz',
    'Schleswig',
    'Schlettau',
    'Schleusingen',
    'Schlieben',
    'Schlitz',
    'Schloß Holte-Stukenbrock',
    'Schlüchtern',
    'Schlüsselfeld',
    'Schmalkalden',
    'Schmallenberg',
    'Schmölln',
    'Schnackenburg',
    'Schnaittenbach',
    'Schneeberg',
    'Schneverdingen',
    'Schongau',
    'Schopfheim',
    'Schorndorf',
    'Schortens',
    'Schotten',
    'Schramberg',
    'Schraplau',
    'Schriesheim',
    'Schrobenhausen',
    'Schrozberg',
    'Schwaan',
    'Schwabach',
    'Schwabmünchen',
    'Schwaigern',
    'Schwalbach am Taunus',
    'Schwalmstadt',
    'Schwandorf',
    'Schwanebeck',
    'Schwarzatal',
    'Schwarzenbach am Wald',
    'Schwarzenbach an der Saale',
    'Schwarzenbek',
    'Schwarzenberg/Erzgeb.',
    'Schwarzenborn',
    'Schwarzheide',
    'Schwedt/Oder',
    'Schweich',
    'Schweinfurt',
    'Schwelm',
    'Schwentinental',
    'Schwerin',
    'Schwerte',
    'Schwetzingen',
    'Schwäbisch Gmünd',
    'Schwäbisch Hall',
    'Schömberg',
    'Schönau im Schwarzwald',
    'Schönau',
    'Schönberg',
    'Schönebeck',
    'Schöneck/Vogtl.',
    'Schönewalde',
    'Schöningen',
    'Schönsee',
    'Schönwald',
    'Schöppenstedt',
    'Schüttorf',
    'Sebnitz',
    'Seehausen',
    'Seeland',
    'Seelow',
    'Seelze',
    'Seesen',
    'Sehnde',
    'Seifhennersdorf',
    'Selb',
    'Selbitz',
    'Seligenstadt',
    'Selm',
    'Selters',
    'Senden',
    'Sendenhorst',
    'Senftenberg',
    'Seßlach',
    'Siegburg',
    'Siegen',
    'Sigmaringen',
    'Simbach am Inn',
    'Simmern/Hunsrück',
    'Sindelfingen',
    'Singen',
    'Sinsheim',
    'Sinzig',
    'Soest',
    'Solingen',
    'Solms',
    'Soltau',
    'Sondershausen',
    'Sonneberg',
    'Sonnewalde',
    'Sonthofen',
    'Sontra',
    'Spaichingen',
    'Spalt',
    'Spangenberg',
    'Speicher',
    'Spenge',
    'Speyer',
    'Spremberg',
    'Springe',
    'Sprockhövel',
    'St. Blasien',
    'St. Georgen im Schwarzwald',
    'St. Ingbert',
    'St. Wendel',
    'Stade',
    'Stadt Wehlen',
    'Stadtallendorf',
    'Stadtbergen',
    'Stadthagen',
    'Stadtilm',
    'Stadtlohn',
    'Stadtoldendorf',
    'Stadtprozelten',
    'Stadtroda',
    'Stadtsteinach',
    'Starnberg',
    'Staufen im Breisgau',
    'Staufenberg',
    'Stavenhagen',
    'Staßfurt',
    'Stein',
    'Steinach',
    'Steinau an der Straße',
    'Steinbach',
    'Steinbach-Hallenberg',
    'Steinfurt',
    'Steinheim an der Murr',
    'Steinheim',
    'Stendal',
    'Sternberg',
    'Stockach',
    'Stolberg',
    'Stollberg/Erzgeb.',
    'Stolpen',
    'Storkow',
    'Straelen',
    'Stralsund',
    'Strasburg',
    'Straubing',
    'Strausberg',
    'Strehla',
    'Stromberg',
    'Stutensee',
    'Stuttgart',
    'Stößen',
    'Stühlingen',
    'Suhl',
    'Sulingen',
    'Sulz am Neckar',
    'Sulzbach-Rosenberg',
    'Sulzbach/Saar',
    'Sulzburg',
    'Sundern',
    'Syke',
    'Sömmerda',
    'Südliches Anhalt',
    'Süßen',
    'Tambach-Dietharz',
    'Tamm',
    'Tangerhütte',
    'Tangermünde',
    'Tann',
    'Tanna',
    'Tauberbischofsheim',
    'Taucha',
    'Taunusstein',
    'Tecklenburg',
    'Tegernsee',
    'Telgte',
    'Teltow',
    'Templin',
    'Tengen',
    'Tessin',
    'Teterow',
    'Tettnang',
    'Teublitz',
    'Teuchern',
    'Teupitz',
    'Teuschnitz',
    'Thale',
    'Thalheim/Erzgeb.',
    'Thannhausen',
    'Tharandt',
    'Themar',
    'Thum',
    'Tirschenreuth',
    'Titisee-Neustadt',
    'Tittmoning',
    'Todtnau',
    'Torgau',
    'Torgelow',
    'Tornesch',
    'Traben-Trarbach',
    'Traunreut',
    'Traunstein',
    'Trebbin',
    'Trebsen/Mulde',
    'Treffurt',
    'Trendelburg',
    'Treuchtlingen',
    'Treuen',
    'Treuenbrietzen',
    'Triberg im Schwarzwald',
    'Tribsees',
    'Trier',
    'Triptis',
    'Trochtelfingen',
    'Troisdorf',
    'Trossingen',
    'Trostberg',
    'Tuttlingen',
    'Twistringen',
    'Töging am Inn',
    'Tönisvorst',
    'Tönning',
    'Tübingen',
    'Uebigau-Wahrenbrück',
    'Ueckermünde',
    'Uelzen',
    'Uetersen',
    'Uffenheim',
    'Uhingen',
    'Ulm',
    'Ulmen',
    'Ulrichstein',
    'Ummerstadt',
    'Unkel',
    'Unna',
    'Unterschleißheim',
    'Usedom',
    'Usingen',
    'Uslar',
    'Vacha',
    'Vaihingen an der Enz',
    'Vallendar',
    'Varel',
    'Vechta',
    'Velbert',
    'Velburg',
    'Velden',
    'Velen',
    'Vellberg',
    'Vellmar',
    'Velten',
    'Verden',
    'Veringenstadt',
    'Verl',
    'Versmold',
    'Vetschau/Spreewald',
    'Viechtach',
    'Viernheim',
    'Viersen',
    'Villingen-Schwenningen',
    'Vilsbiburg',
    'Vilseck',
    'Vilshofen an der Donau',
    'Visselhövede',
    'Vlotho',
    'Voerde',
    'Vogtsburg im Kaiserstuhl',
    'Vohburg an der Donau',
    'Vohenstrauß',
    'Volkach',
    'Volkmarsen',
    'Vreden',
    'Vöhrenbach',
    'Vöhringen',
    'Völklingen',
    'Wachenheim an der Weinstraße',
    'Wadern',
    'Waghäusel',
    'Wahlstedt',
    'Waiblingen',
    'Waibstadt',
    'Waischenfeld',
    'Waldbröl',
    'Waldeck',
    'Waldenbuch',
    'Waldenburg',
    'Waldenburg',
    'Waldershof',
    'Waldheim',
    'Waldkappel',
    'Waldkirch',
    'Waldkirchen',
    'Waldkraiburg',
    'Waldmohr',
    'Waldmünchen',
    'Waldsassen',
    'Waldshut-Tiengen',
    'Walldorf',
    'Walldürn',
    'Wallenfels',
    'Walsrode',
    'Waltershausen',
    'Waltrop',
    'Wanfried',
    'Wangen im Allgäu',
    'Wanzleben-Börde',
    'Warburg',
    'Waren',
    'Warendorf',
    'Warin',
    'Warstein',
    'Wassenberg',
    'Wasserburg am Inn',
    'Wassertrüdingen',
    'Wasungen',
    'Wedel',
    'Weener',
    'Wegberg',
    'Wegeleben',
    'Wehr',
    'Weida',
    'Weiden in der Oberpfalz',
    'Weikersheim',
    'Weil am Rhein',
    'Weil der Stadt',
    'Weilburg',
    'Weilheim an der Teck',
    'Weilheim in Oberbayern',
    'Weimar',
    'Weingarten',
    'Weinheim',
    'Weinsberg',
    'Weinstadt',
    'Weismain',
    'Weiterstadt',
    'Weißenberg',
    'Weißenburg in Bayern',
    'Weißenfels',
    'Weißenhorn',
    'Weißensee',
    'Weißenstadt',
    'Weißenthurm',
    'Weißwasser/O.L.',
    'Welzheim',
    'Welzow',
    'Wemding',
    'Wendlingen am Neckar',
    'Werben',
    'Werdau',
    'Werder',
    'Werdohl',
    'Werl',
    'Werlte',
    'Wermelskirchen',
    'Wernau',
    'Werne',
    'Werneuchen',
    'Wernigerode',
    'Werra-Suhl-Tal',
    'Wertheim',
    'Werther',
    'Wertingen',
    'Wesel',
    'Wesenberg',
    'Wesselburen',
    'Wesseling',
    'Westerburg',
    'Westerstede',
    'Wetter',
    'Wetter',
    'Wettin-Löbejün',
    'Wetzlar',
    'Widdern',
    'Wiehl',
    'Wiesbaden',
    'Wiesensteig',
    'Wiesloch',
    'Wiesmoor',
    'Wildau',
    'Wildberg',
    'Wildenfels',
    'Wildeshausen',
    'Wilhelmshaven',
    'Wilkau-Haßlau',
    'Willebadessen',
    'Willich',
    'Wilsdruff',
    'Wilster',
    'Wilthen',
    'Windischeschenbach',
    'Windsbach',
    'Winnenden',
    'Winsen',
    'Winterberg',
    'Wipperfürth',
    'Wirges',
    'Wismar',
    'Wissen',
    'Witten',
    'Wittenberg',
    'Wittenberge',
    'Wittenburg',
    'Wittichenau',
    'Wittingen',
    'Wittlich',
    'Wittmund',
    'Wittstock/Dosse',
    'Witzenhausen',
    'Woldegk',
    'Wolfach',
    'Wolfenbüttel',
    'Wolfhagen',
    'Wolframs-Eschenbach',
    'Wolfratshausen',
    'Wolfsburg',
    'Wolfstein',
    'Wolgast',
    'Wolkenstein',
    'Wolmirstedt',
    'Worms',
    'Wriezen',
    'Wunsiedel',
    'Wunstorf',
    'Wuppertal',
    'Wurzbach',
    'Wurzen',
    'Wustrow',
    'Wyk auf Föhr',
    'Wächtersbach',
    'Wörrstadt',
    'Wörth am Main',
    'Wörth am Rhein',
    'Wörth an der Donau',
    'Wülfrath',
    'Würselen',
    'Würzburg',
    'Xanten',
    'Zahna-Elster',
    'Zarrentin am Schaalsee',
    'Zehdenick',
    'Zeil am Main',
    'Zeitz',
    'Zell',
    'Zell am Harmersbach',
    'Zell im Wiesental',
    'Zella-Mehlis',
    'Zerbst/Anhalt',
    'Zeulenroda-Triebes',
    'Zeven',
    'Ziegenrück',
    'Zierenberg',
    'Ziesar',
    'Zirndorf',
    'Zittau',
    'Zossen',
    'Zschopau',
    'Zweibrücken',
    'Zwenkau',
    'Zwickau',
    'Zwiesel',
    'Zwingenberg',
    'Zwönitz',
    'Zörbig',
    'Zülpich',
    'Öhringen',
    'Östringen',
    'Übach-Palenberg',
    'Überlingen'
]

module.exports = {
    about,
    menu,
    rules,
    commands,
    settingsBanner,
    options,
    cities
}
